# see https://github.com/topics/pre-commit-hook for more
default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/akaihola/darker
    rev: 1.6.1
    hooks:
    -   id: darker
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: ["--py310-plus"]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.241'
  hooks:
    - id: ruff
